name: SAM CABAN DOT COM
favicon: null
layout_spectrum: 0.6598758569452912
typography_spectrum: 0.7778746814001352
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.06633227854035795
  lightness: 0.26418102579191327
  saturation: 0.2958651736844331
  rhythmicContrast: 0.1893405499868095
purpose: []
